[envs.base]
command = "python ../test_inputs.py one | python {filename}"

[envs.transformed]
command = "python ../../transform.py pass {filename}; python ../test_inputs.py one | python {base}_pa_qe.py"
